[workspace]
members = ["packages/*", "contracts/*"]

[workspace.package]
version       = "0.16.0"
edition       = "2021"
license       = "Apache-2.0"
repository    = "https://github.com/CosmWasm/cw-nfts"
homepage      = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[workspace.dependencies]
cosmwasm-schema = "1.1.5"
cosmwasm-std    = "1.1.5"
cw2             = "0.16.0"
cw20            = "0.16.0"
cw721           = { version = "0.16.0", path = "./packages/cw721" }
inns721-base      = { version = "0.16.0", path = "./contracts/inns721-base" }
cw-storage-plus = "0.16.0"
cw-utils        = "0.16.0"
schemars        = "0.8.10"
serde           = { version = "1.0.140", default-features = false, features = ["derive"] }
thiserror       = "1.0.31"

[profile.release.package.inns721-base]
codegen-units = 1
incremental = false

[profile.release.package.inns721-metadata-onchain]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
